apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  labels:
    addressSpaceType: standard
    namespace: amq-online
    type: address-space
  name: demo-space
  namespace: amqp-demo
spec:
  type: standard
  plan: standard-small
  authenticationService:
    name: standard-authservice
  endpoints:
  - name: messaging
    service: messaging
    expose:
      type: route
      routeServicePort: amqps
      routeTlsTermination: passthrough
    exports:
    - kind: ConfigMap
      name: spring-boot-camel-amq-config
    cert:
      provider: openshift