apiVersion: user.enmasse.io/v1beta1
kind: MessagingUser
metadata:
  name: demo-space.demo-user
spec:
  username: demo-user
  authentication:
    type: password
    password: cGFzc3dvcmQ= # Base64 encode of 'password'
  authorization:
    - addresses:
        - '*'
        - mysub
        - mysubscription
      operations:
        - recv
        - send
    - addresses: []
      operations:
        - manage
    - addresses: []
      operations:
        - view
